name: Rails CI

on: [push]

jobs:
  rails-tests:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      
      - name: Initialize database
        run: |
          rails db:drop
          rails db:create
          rails db:migrate

      - name: Run tests
        run: |
          rspec spec