name: Rails CI

on: [push]

jobs:
  rails-tests:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: prod_net_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 127.0.0.1

    services:
      postgresql:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      
      - name: Install rails
        run: |
          gem install rails
      
      - name: Install dependencies
        run: |
          bundle install
      
      - name: Initialize database
        run: |
          rails db:drop
          rails db:create
          rails db:migrate
      
      - name: Precompile Assets
        run: bin/rails assets:precompile

      - name: Run tests
        run: |
          bundle exec rspec